#!/bin/bash
cd `dirname $0`
#svn up .

for B in 38 39 40 41 42
do
    if test ! -e fost-base-rc/Boost/1_${B}_0
    then {
        cd fost-base-rc/Boost
        ln -s ../../Boost/1_${B}_0
        cd ../..
    }
    fi

    if test ! -e fost-base-rc/Boost/boost/include/boost-1_$B
    then {
        fost-base-rc/Boost/build $B
    }
    fi

    if fost-base-rc/Boost/install $B 0 &&
        fost-base-rc/fost-base/compile all
    then {
        echo OK fost-base-rc with Boost 1.$B.0
    } else {
        echo FAILED fost-base-rc with Boost 1.$B.0
        exit 1
    }
    fi
done
