#!/bin/bash
export LIBRARY_TO_BUILD=fost-windows
cd `dirname $0`/${LIBRARY_TO_BUILD}-stable && \
	svn up && \
	Boost/install maverick && \
	svn merge https://svn.felspar.com/public/${LIBRARY_TO_BUILD}/trunk && \
	svn diff ${LIBRARY_TO_BUILD}/ChangeLog
